ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - canvas

overrides:
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
  tar@=7.5.1: '>=7.5.2'
